'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    'przez narzędzie, takie jak ResGen lub Visual Studio.
    'Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    'z opcją /str lub ponownie utwórz projekt VS.
    '''<summary>
    '''  Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Bolt2Optim.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        '''  przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property idksiegowego() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("idksiegowego", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property marm_pl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marm.pl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property optima_konfiguracja_rozproszona() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("optima_konfiguracja_rozproszona", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        '''  &lt;xsl:output method=&quot;text&quot; encoding=&quot;utf-8&quot; /&gt;
        '''
        '''  &lt;xsl:param name=&quot;delim&quot; select=&quot;&apos;,&apos;&quot; /&gt;
        '''  &lt;xsl:param name=&quot;quote&quot; select=&quot;&apos;&amp;quot;&apos;&quot; /&gt;
        '''  &lt;xsl:param name=&quot;break&quot; select=&quot;&apos;&amp;#xA;&apos;&quot; /&gt;
        '''&lt;xsl:param name=&quot;quotehex&quot; select=&quot;&apos;&amp;#x22;&apos;&quot; /&gt;  
        '''
        '''&lt;!-- change cr+lf to br --&gt;
        '''&lt;xsl:template name=&quot;breakht&quot;&gt;
        '''  &lt;xsl:param name=&quot;text&quot; select=&quot;string(.)&quot;/&gt;
        '''  &lt;xsl:choose&gt;
        '''    &lt;xsl:when test=&quot;contains($text, &apos;&amp;#xa;&apos;)&quot;&gt;
        '''      &lt;xsl:value-of select=&quot;nor [obcięto pozostałą część ciągu]&quot;;.
        '''</summary>
        Friend ReadOnly Property xml2csv() As String
            Get
                Return ResourceManager.GetString("xml2csv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        '''    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        '''&gt;
        '''    &lt;xsl:output indent=&quot;yes&quot; method=&quot;xml&quot; omit-xml-declaration=&quot;no&quot; version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; /&gt;
        '''    &lt;xsl:strip-space elements=&quot;*&quot; /&gt;
        '''  &lt;xsl:param name=&quot;pOptZrd&quot;/&gt;
        '''  &lt;xsl:param name=&quot;pOptDoc&quot;/&gt;
        '''  &lt;xsl:param name=&quot;pFixedKod&quot;/&gt;
        '''  &lt;xsl:param name=&quot;pFixedMiasto&quot;/&gt;
        '''  &lt;xsl:param name=&quot;pNIPclean&quot;/&gt;
        '''
        ''' [obcięto pozostałą część ciągu]&quot;;.
        '''</summary>
        Friend ReadOnly Property XSLTFile1() As String
            Get
                Return ResourceManager.GetString("XSLTFile1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
